import type {
  AdminScenarioRow,
  EngagementMetric,
  GroupDecisionSignal,
  Insight,
  PilotKpi,
  PortalSummary,
  SkillCoverage,
  YouthMissionSubmission,
} from '../../../types/admin.js';

// TODO(Scenario, Choice): Add schema models and authenticated endpoints for scenario authoring and publishing.
// TODO(Session, Squad, Participant, GuardianProgress): Connect telemetry pipeline and persistent analytics for cohort metrics.
// TODO: Missing database models for YouthMission, SubmissionReview, AuditLog, and KpiEvaluation.

export const MOCK_ADMIN_SCENARIOS: AdminScenarioRow[] = [
  {
    id: 'scn_shop_theft_01',
    title: 'The Dare at Checkout',
    category: 'Shop Theft & Peer Pressure',
    targetGroup: 'Secondary',
    status: 'LIVE',
    safeDecisionRate: 74,
    previousSafeDecisionRate: 65,
    responses: 3960,
    competencies: ['SPOT', 'IDENTIFY', 'LEAD'],
    updatedBy: 'Content Team',
    updatedOn: '09 Aug 2026',
    isFlashMission: false,
  },
  {
    id: 'scn_money_mule_01',
    title: 'Easy Money?',
    category: 'Money Mule Recruitment',
    targetGroup: 'Post-Secondary / Tertiary',
    status: 'LIVE',
    safeDecisionRate: 61,
    previousSafeDecisionRate: 54,
    responses: 2841,
    competencies: ['SPOT', 'HOLD', 'EVALUATE'],
    updatedBy: 'Content Team',
    updatedOn: '12 Aug 2026',
    isFlashMission: false,
  },
  {
    id: 'scn_account_sharing_01',
    title: 'Just Use Mine',
    category: 'Account Sharing',
    targetGroup: 'Secondary',
    status: 'LIVE',
    safeDecisionRate: 58,
    previousSafeDecisionRate: 60,
    responses: 2210,
    competencies: ['EVALUATE', 'HOLD'],
    updatedBy: 'Content Team',
    updatedOn: '14 Aug 2026',
    isFlashMission: false,
  },
  {
    id: 'scn_ecom_01',
    title: 'Concert Tickets, Cash Only',
    category: 'E-Commerce Scam',
    targetGroup: 'All Youth Bands',
    status: 'LIVE',
    safeDecisionRate: 82,
    previousSafeDecisionRate: 80,
    responses: 5120,
    competencies: ['SPOT', 'HOLD'],
    updatedBy: 'Content Team',
    updatedOn: '02 Aug 2026',
    isFlashMission: false,
  },
  {
    id: 'scn_peer_mule_01',
    title: "Jayden's Offer",
    category: 'Peer Shield · Money Mule',
    targetGroup: 'Post-Secondary / Tertiary',
    status: 'LIVE',
    safeDecisionRate: 71,
    previousSafeDecisionRate: 68,
    responses: 1902,
    competencies: ['DEFEND', 'LEAD'],
    updatedBy: 'Content Team',
    updatedOn: '11 Aug 2026',
    isFlashMission: false,
  },
  {
    id: 'scn_job_scam_01',
    title: 'No Experience Needed',
    category: 'Job Scam',
    targetGroup: 'Post-Secondary / Tertiary',
    status: 'LIVE',
    safeDecisionRate: 66,
    previousSafeDecisionRate: 62,
    responses: 1874,
    competencies: ['IDENTIFY', 'EVALUATE'],
    updatedBy: 'Content Team',
    updatedOn: '07 Aug 2026',
    isFlashMission: false,
  },
  {
    id: 'scn_vape_01',
    title: 'Just Hold It For Me',
    category: 'Vape Possession',
    targetGroup: 'Secondary',
    status: 'LIVE',
    safeDecisionRate: 79,
    previousSafeDecisionRate: 76,
    responses: 3315,
    competencies: ['HOLD', 'DEFEND'],
    updatedBy: 'Content Team',
    updatedOn: '05 Aug 2026',
    isFlashMission: false,
  },
  {
    id: 'scn_qr_01',
    title: 'Carpark QR Swap',
    category: 'Phishing QR',
    targetGroup: 'All Youth Bands',
    status: 'LIVE',
    safeDecisionRate: 55,
    previousSafeDecisionRate: 55,
    responses: 812,
    competencies: ['SPOT', 'IDENTIFY'],
    updatedBy: 'Content Team',
    updatedOn: '18 Aug 2026',
    isFlashMission: true,
  },
  {
    id: 'scn_gaming_01',
    title: 'Free Skins, Just Log In',
    category: 'Account Takeover',
    targetGroup: 'Primary / Early Secondary',
    status: 'LIVE',
    safeDecisionRate: 69,
    previousSafeDecisionRate: 64,
    responses: 4408,
    competencies: ['SPOT', 'EVALUATE'],
    updatedBy: 'Content Team',
    updatedOn: '01 Aug 2026',
    isFlashMission: false,
  },
  {
    id: 'scn_loan_01',
    title: 'Runner for a Day',
    category: 'Unlicensed Moneylending',
    targetGroup: 'Post-Secondary / Tertiary',
    status: 'LIVE',
    safeDecisionRate: 63,
    previousSafeDecisionRate: 58,
    responses: 1544,
    competencies: ['EVALUATE', 'LEAD'],
    updatedBy: 'Content Team',
    updatedOn: '10 Aug 2026',
    isFlashMission: false,
  },
  {
    id: 'scn_peer_theft_01',
    title: 'Cover For Me',
    category: 'Peer Shield · Shop Theft',
    targetGroup: 'Secondary',
    status: 'LIVE',
    safeDecisionRate: 77,
    previousSafeDecisionRate: 73,
    responses: 2670,
    competencies: ['DEFEND'],
    updatedBy: 'Content Team',
    updatedOn: '08 Aug 2026',
    isFlashMission: false,
  },
  {
    id: 'scn_deepfake_01',
    title: "That's Not Really Them",
    category: 'Impersonation',
    targetGroup: 'Secondary',
    status: 'LIVE',
    safeDecisionRate: 61,
    previousSafeDecisionRate: 57,
    responses: 1180,
    competencies: ['IDENTIFY', 'HOLD'],
    updatedBy: 'Content Team',
    updatedOn: '16 Aug 2026',
    isFlashMission: true,
  },
  {
    id: 'scn_parcel_01',
    title: 'Your Parcel Is Held',
    category: 'Phishing Link',
    targetGroup: 'Primary / Early Secondary',
    status: 'LIVE',
    safeDecisionRate: 64,
    previousSafeDecisionRate: 59,
    responses: 2054,
    competencies: ['SPOT', 'HOLD'],
    updatedBy: 'Content Team',
    updatedOn: '13 Aug 2026',
    isFlashMission: false,
  },
  {
    id: 'scn_otp_01',
    title: 'Just Read Me the Code',
    category: 'Credential Request',
    targetGroup: 'All Youth Bands',
    status: 'LIVE',
    safeDecisionRate: 57,
    previousSafeDecisionRate: 52,
    responses: 1663,
    competencies: ['EVALUATE', 'HOLD'],
    updatedBy: 'Content Team',
    updatedOn: '15 Aug 2026',
    isFlashMission: false,
  },
  {
    id: 'scn_group_chat_01',
    title: 'The Group Chat Job',
    category: 'Money Mule · Think–Vote–Explain',
    targetGroup: 'Secondary',
    status: 'LIVE',
    safeDecisionRate: 68,
    previousSafeDecisionRate: 61,
    responses: 946,
    competencies: ['LEAD', 'DEFEND'],
    updatedBy: 'Content Team',
    updatedOn: '19 Aug 2026',
    isFlashMission: false,
  },
  {
    id: 'scn_draft_01',
    title: 'Borrowed Login',
    category: 'Account Sharing',
    targetGroup: 'Secondary',
    status: 'DRAFT',
    safeDecisionRate: 0,
    previousSafeDecisionRate: 0,
    responses: 0,
    competencies: ['HOLD'],
    updatedBy: 'Content Team',
    updatedOn: '17 Aug 2026',
    isFlashMission: false,
  },
  {
    id: 'scn_sched_01',
    title: 'The Group Buy',
    category: 'E-Commerce Scam',
    targetGroup: 'All Youth Bands',
    status: 'SCHEDULED',
    safeDecisionRate: 0,
    previousSafeDecisionRate: 0,
    responses: 0,
    competencies: ['SPOT', 'EVALUATE'],
    updatedBy: 'Content Team',
    updatedOn: '16 Aug 2026',
    isFlashMission: false,
  },
];

export const MOCK_PORTAL_PARTICIPANTS = 1248;

export const MOCK_INSIGHTS: Insight[] = [
  {
    id: 'in_support',
    kind: 'SUPPORT',
    label: 'Topic requiring more support',
    subject: 'Account Sharing',
    value: '58%',
    note: 'Safer-decision rate is the lowest across live content. Consider an additional teaching scenario.',
  },
  {
    id: 'in_improved',
    kind: 'IMPROVED',
    label: 'Most improved',
    subject: 'Shop Theft & Peer Pressure',
    value: '+9 pts',
    note: 'Improvement since the revised debrief was published this cycle.',
  },
  {
    id: 'in_peer',
    kind: 'PEER_SHIELD',
    label: 'Peer Shield',
    subject: 'Appropriate intervention chosen',
    value: '72%',
    note: 'Across all Peer Shield content. Private-warning and seek-help options combined.',
  },
];

export const MOCK_SKILL_COVERAGE: SkillCoverage[] = [
  { competency: 'SPOT', coverage: 82, scenarios: 7 },
  { competency: 'HOLD', coverage: 65, scenarios: 7 },
  { competency: 'IDENTIFY', coverage: 71, scenarios: 3 },
  { competency: 'EVALUATE', coverage: 67, scenarios: 6 },
  { competency: 'LEAD', coverage: 79, scenarios: 4 },
  { competency: 'DEFEND', coverage: 73, scenarios: 4 },
];

export const SAFEGUARDS: string[] = [
  'Aggregate learning analytics only',
  'No crime prediction',
  'No individual youth profiling',
  'No real banking or Singpass credentials used in scenarios',
  'Simulated scenario data',
  'Youth-submitted ideas reviewed before drafting — no direct publication',
  'Youth submissions carry a pseudonym and a band, never an identity',
  'Group discussion figures are simulated, never participant records',
];

export const ENGAGEMENT_METRICS: EngagementMetric[] = [
  {
    id: 'eng_session',
    label: 'Session completion',
    value: '84%',
    note: 'Facilitated sessions carried through to the closing debrief.',
  },
  {
    id: 'eng_scenario',
    label: 'Scenario completion',
    value: '79%',
    note: 'Scenarios opened that reached a committed decision and its debrief.',
  },
  {
    id: 'eng_replay',
    label: 'Voluntary replay',
    value: '31%',
    note: 'Activities re-run by choice, with no additional reward for doing so.',
  },
  {
    id: 'eng_duration',
    label: 'Average participation duration',
    value: '18m 40s',
    note: 'Time spent in activities per session. Aggregate, never per participant.',
  },
];

export const PILOT_KPIS: PilotKpi[] = [
  {
    id: 'kpi_risk',
    number: 1,
    name: 'Risk Recognition',
    measures: 'Whether a young person notices the warning signs in a situation.',
    method: 'Pre and post learning checks, plus clue-recognition activities in the city.',
    status: 'DEMONSTRATED',
  },
  {
    id: 'kpi_decision',
    number: 2,
    name: 'Decision Accuracy',
    measures: 'Whether a safer response is chosen, including in unfamiliar situations.',
    method: 'Scenario choices, and transfer questions that move the same skill to a new situation.',
    status: 'DEMONSTRATED',
  },
  {
    id: 'kpi_consequence',
    number: 3,
    name: 'Consequence Awareness',
    measures: 'Whether the delayed cost of a decision can be named while the reward is still visible.',
    method: 'Delayed Consequence Engine, prediction activities and learning checks.',
    status: 'DEMONSTRATED',
  },
  {
    id: 'kpi_peer',
    number: 4,
    name: 'Peer Intervention Confidence',
    measures: 'Whether a young person would act when it is a friend at risk, and how.',
    method: 'Peer Shield scenarios, facilitated group questions and the peer-intervention learning checks.',
    status: 'DEMONSTRATED',
  },
  {
    id: 'kpi_retention',
    number: 5,
    name: 'Retention',
    measures: 'Whether the recognition and reasoning hold weeks after the session.',
    method: 'A 2–4 week follow-up check during the pilot, where participant re-engagement is feasible.',
    status: 'PLANNED',
  },
  {
    id: 'kpi_engagement',
    number: 6,
    name: 'Engagement',
    measures: 'Whether the experience is completed, returned to and stayed with.',
    method: 'Session and scenario completion, voluntary replay and average participation duration.',
    status: 'SIMULATED',
  },
];

export const RETENTION_LIMITATION =
  'Follow-up measurement needs participants to be re-engaged two to four weeks after a facilitated session, inside a controlled pilot. This build has no cohort, no scheduling and no participant contact, so it cannot measure retention — and no retention figure is shown anywhere in this build.';

export const MOCK_YOUTH_SUBMISSIONS: YouthMissionSubmission[] = [
  {
    id: 'ym_001',
    title: 'The Study Group That Wanted My Login',
    category: 'Credential Request',
    suggestedBand: 'Secondary',
    proposedCompetency: 'EVALUATE',
    summary:
      'Someone in a study group chat asks for your school portal login so they can “download the notes for everyone”. It sounds helpful and everyone in the chat agrees it is fine.',
    intendedLesson:
      'A request can be socially normal and still be a bad idea. Whatever happens on that login is under your name.',
    submittedBy: 'Contributor 7F2A',
    submittedOn: '18 Aug 2026',
    submitterBand: 'Secondary',
    status: 'AWAITING_REVIEW',
    safeguardingFlags: [
      'Uses a school system as the setting — check it cannot identify a real school',
      'No credential format or real portal should appear in the scenario text',
    ],
  },
  {
    id: 'ym_002',
    title: 'Reselling Concert Tickets I Never Had',
    category: 'E-Commerce Scam',
    suggestedBand: 'Post-Secondary / Tertiary',
    proposedCompetency: 'IDENTIFY',
    summary:
      'You are offered a “bulk buy” of resale tickets to flip for profit. The seller wants payment first and says the tickets transfer after.',
    intendedLesson:
      'Being the seller in a scam is a role people fall into, not only one they choose. Handling money for someone else’s listing makes it yours.',
    submittedBy: 'Contributor B41C',
    submittedOn: '17 Aug 2026',
    submitterBand: 'Post-Secondary / Tertiary',
    status: 'AWAITING_REVIEW',
    safeguardingFlags: [
      'Frames the player as a potential participant — the debrief must not read as instructions',
      'Avoid naming a real ticketing platform',
    ],
  },
  {
    id: 'ym_003',
    title: 'My Cousin Needs a Bank Account',
    category: 'Money Mule Recruitment',
    suggestedBand: 'Post-Secondary / Tertiary',
    proposedCompetency: 'HOLD',
    summary:
      'A family member — not a stranger — asks to use your account “just this once” because theirs is frozen. Saying no feels like accusing them of something.',
    intendedLesson:
      'The hardest version of this is not a stranger. Family pressure removes the option of just blocking them.',
    submittedBy: 'Contributor 9D0E',
    submittedOn: '16 Aug 2026',
    submitterBand: 'Post-Secondary / Tertiary',
    status: 'AWAITING_REVIEW',
    safeguardingFlags: [
      'Family setting — the debrief must not push a young person to confront a relative',
      'Needs a route to trusted help that does not require accusing anybody',
    ],
  },
  {
    id: 'ym_004',
    title: 'Free Robux Generator',
    category: 'Account Takeover',
    suggestedBand: 'Primary / Early Secondary',
    proposedCompetency: 'SPOT',
    summary:
      'A video promises free in-game currency if you log in through a link in the description. Half the class has already tried it.',
    intendedLesson:
      'If everyone is doing it, that is not evidence it works — it is evidence the approach is working on people.',
    submittedBy: 'Contributor 22B8',
    submittedOn: '15 Aug 2026',
    submitterBand: 'Secondary',
    status: 'CHANGES_REQUESTED',
    reviewedBy: 'Content Lead',
    reviewNote:
      'Good instinct and the right age band. Needs rewriting without the branded currency name, and the debrief should not describe how the generator page works.',
    safeguardingFlags: [
      'Names a real game currency — must be genericised before drafting',
      'Younger band: keep the language simple and avoid technical detail',
    ],
  },
  {
    id: 'ym_005',
    title: 'The Group Chat That Turned On Someone',
    category: 'Peer Shield · Harassment',
    suggestedBand: 'Secondary',
    proposedCompetency: 'DEFEND',
    summary:
      'A class chat starts piling on one person. You have not said anything, but you are still in the chat and you have not left either.',
    intendedLesson:
      'Being a silent witness is a position, not a neutral one. There is something to do that is not a confrontation.',
    submittedBy: 'Contributor 5A17',
    submittedOn: '14 Aug 2026',
    submitterBand: 'Secondary',
    status: 'CONVERTED',
    reviewedBy: 'Content Lead',
    reviewNote:
      'Converted to a Peer Shield draft. Held for a safeguarding read before it goes any further — harassment content needs a support route in the debrief.',
    safeguardingFlags: [
      'Harassment theme — debrief must route to trusted help, not to retaliation',
      'Must not model the pile-on language itself in the transcript',
    ],
  },
  {
    id: 'ym_006',
    title: 'Selling My Old Account for Cash',
    category: 'Account Sharing',
    suggestedBand: 'Secondary',
    proposedCompetency: 'EVALUATE',
    summary:
      'Someone offers to buy a gaming account you have stopped using. It feels like selling something you own.',
    intendedLesson:
      'An account is not a possession you can hand over cleanly. It stays linked to the person who made it.',
    submittedBy: 'Contributor E3C9',
    submittedOn: '13 Aug 2026',
    submitterBand: 'Secondary',
    status: 'AWAITING_REVIEW',
    safeguardingFlags: [
      'Check the debrief does not read as advice on how to sell an account safely',
    ],
  },
  {
    id: 'ym_007',
    title: "Rate My Friend's Scam Message",
    category: 'Uncategorised',
    suggestedBand: 'All Youth Bands',
    proposedCompetency: 'SPOT',
    summary:
      'A submission proposing that players upload real messages they have received and have other players rate how suspicious they are.',
    intendedLesson:
      'Submitter’s stated aim was to use real examples so the content stays current.',
    submittedBy: 'Contributor 08FD',
    submittedOn: '11 Aug 2026',
    submitterBand: 'Post-Secondary / Tertiary',
    status: 'REJECTED',
    reviewedBy: 'Content Lead',
    reviewNote:
      'Not taken forward as proposed. Player-uploaded real messages would put personal data and identifiable third parties into the platform, and youth-rating-youth content is outside what this programme will do. The underlying idea — keeping examples current — is being picked up through the authored library instead.',
    safeguardingFlags: [
      'User-generated uploads would carry personal data and identifiable third parties',
      'Peer rating of peer content is out of scope for this programme',
    ],
  },
];

export const MOCK_GROUP_DECISION_SIGNALS: GroupDecisionSignal[] = [
  {
    id: 'gds_group_chat_job',
    question: 'The Group Chat Job — what should the group do?',
    band: 'Secondary',
    responses: 168,
    initialSafePct: 25,
    finalSafePct: 61,
    reconsideredPct: 44,
    topFactor: 'He would lose face in front of the group',
  },
  {
    id: 'gds_mule_family',
    question: 'A relative asks to use your bank account — do you agree?',
    band: 'Post-Secondary / Tertiary',
    responses: 124,
    initialSafePct: 48,
    finalSafePct: 66,
    reconsideredPct: 27,
    topFactor: 'Saying no feels like accusing them',
  },
  {
    id: 'gds_ecom',
    question: 'A seller wants payment off-platform for a discount — pay?',
    band: 'All Youth Bands',
    responses: 211,
    initialSafePct: 63,
    finalSafePct: 71,
    reconsideredPct: 15,
    topFactor: 'The discount is the whole reason to leave the platform',
  },
];

export function derivePortalSummary(rows: AdminScenarioRow[]): PortalSummary {
  const live = rows.filter((r) => r.status === 'LIVE');
  const scored = live.filter((r) => r.responses > 0);
  const average = scored.length
    ? Math.round(
        scored.reduce((sum, r) => sum + r.safeDecisionRate, 0) / scored.length,
      )
    : 0;
  return {
    activeScenarios: live.length,
    participants: MOCK_PORTAL_PARTICIPANTS,
    averageSafeDecisionRate: average,
    needsReview: scored.filter((r) => r.safeDecisionRate < 60).length,
  };
}
